### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by CodeJjang** [tszarzynski/cra-append-sw#11]
Hi,
Can you please provide a demo code regarding how to alter the service-worker original logic?  
I managed to append code, and I can't manage to exclude some URL paths from being cached.  

I tried the following code:
```
self.addEventListener('fetch', function (event) {
    console.log("Fetch url:", event.request.url); // tslint:disable-line
    if (event.request.url.indexOf('auth') > -1) {
         console.log("Returning false"); // tslint:disable-line
         return false;
     }
});
```

Logs are written, but the path is being cached anyway.

Also, if I want to replace the whole service worker CRA code, how can I predict webpack's file names ahead? I don't want to eject for this.

**Comment by tszarzynski** [comment]
To alter the logic of the original service worker you'll have to replace it completely. Then you can implement your logic in your own SW or use something like [sw-precache](https://github.com/GoogleChromeLabs/sw-precache).

To completely replace the original SW you have to run the script with `--mode replace` option. It will then simply overwrite `build/service-worker.js` after CRA build script is done.

**Comment by CodeJjang** [comment]
@tszarzynski But then I can't predict the webpack's file names, which are generated into the SW code.

**Comment by tszarzynski** [comment]
@CodeJjang I played a little bit and this piece of code seems to do the job:

```
var blacklist = ['index.html'];

for (let [key, val] of urlsToCacheKeys) {
  if (blacklist.some(e => val.match(e))) {
    urlsToCacheKeys.delete(key);
  }
}
```

You just have to append it to original SW.

**Comment by temitope** [comment]
@tszarzynski thanks for laying this out quite clearly with the two options. Would we be able to use this module to still append the code as you suggested, or do we need to manually alter the `service-worker.js` generated by CRA? Basically wondering if the appended custom file that this module appends has scope of the `urlsToCacheKeys` object. Will try :)

**Comment by CodeJjang** [comment]
@temitope  Please update here, since then I completely removed the `service-worker` code from my project but if it works I'll return it :)

**Comment by temitope** [comment]
@CodeJjang absolutely my pleasure. So first off my assumption did not work but I was able to do url-specific non-caching so I am happy :) I was reading over all of your guys' work (thank you) and found out it's pretty simple to use `sw-precache` as @tszarzynski laid out. At first it looked daunting, but if you had already implemented this lib then it is the same difficulty. The most important part is setting up the config file (i will paste below). 

1. I installed via `yarn sw-precache`
2. I specified the config file which indicates which 
URLs to not cache
3. modify the package.json build command to make sure sw-precache runs and overwrites the default `service-worker.js` file in the build

This tutorial is super helpful - https://medium.freecodecamp.org/how-to-build-a-pwa-with-create-react-app-and-custom-service-workers-376bd1fdc6d3

_sw-precache-config.js_ is the config file that was specified in build script update in _package.json_. Example below seems to work well for create-react-app. The part we are concerned with is the **runtimeCaching** key/option.
```
module.exports = {
    staticFileGlobs: [
        'build/*.html',
        'build/manifest.json',
        'build/static/**/!(*map*)',
    ],
    staticFileGlobsIgnorePatterns: [/\.map$/, /asset-manifest\.json$/],
    swFilePath: './build/service-worker.js',
    stripPrefix: 'build/',
    runtimeCaching: [
        {
            urlPattern: /dont_cache_me1/,
            handler: 'networkOnly'
        }, {
            urlPattern: /dont_cache_me2/,
            handler: 'networkOnly'
        }
    ]
}
```

**Comment by pcegarra** [comment]
> @CodeJjang I played a little bit and this piece of code seems to do the job:
> 
> ```
> var blacklist = ['index.html'];
> 
> for (let [key, val] of urlsToCacheKeys) {
>   if (blacklist.some(e => val.match(e))) {
>     urlsToCacheKeys.delete(key);
>   }
> }
> ```
> You just have to append it to original SW.

The log says something like unable to found urlsToCacheKeys
