### ISSUE TITLE
can't resolve module babel loader

### ISSUE THREAD

**Issue by goldylucks** [tszarzynski/cra-append-sw#18]
```bash
# package.json/scripts
"start": "HTTPS=true PORT=3001 react-app-rewired start && cra-append-sw --mode replace ./custom-sw.js"
"build": "react-app-rewired build && cra-append-sw ./src/append-sw.js",

$ yarn start #this works but doesn't do anything regarding the sw, I get CRA's noop SW
$ yarn build
ERROR in multi ./src/append-sw.js
Module not found: Error: Can't resolve 'babel-loader' in '/home/goldy/apps/veganprince/client'
```

Notice also the webpack hash error:
![image](https://user-images.githubusercontent.com/6963212/60000645-4c774f80-966d-11e9-8dcf-0bd113f14831.png)

if I remove the `src` from the destination in the build script, I get `Module not found: Error: Can't resolve './append-sw.js' in '/home/goldy/apps/veganprince/client'`

any ideas how to proceed?

Thanks!

**Comment by goldylucks** [comment]
```bash
$ cat client/node_modules/cra-append-sw/package.json | grep version
"version": "2.6.1",
```

I'm passing `--skip-compile` now and it works

**Comment by tszarzynski** [comment]
I haven't tested the script with `react-app-rewired`.

I'm guessing there are some npm dependency conflicts involving babel plugins. I had that issue originally with create-react-app setup. 

`--skip-compile` is omitting the compilation (no babel involved) and the error no longer occurs.

Check your npm packages and make sure there are no conflicts.

**Comment by goldylucks** [comment]
closing this since `--skip-compile` solved the issue for me, and regardless I might eject from CRA soom.

Thanks again for the help!

**Comment by m-sterspace** [comment]
FYI I'm having the same issue with a freshly created "CRA". --skip-compile seems to work, but coming in fresh it took me a while to find this page / solution.

**Comment by whmountains** [comment]
An out-of-date react-scripts can also cause this problem.

**Comment by joaomantovani** [comment]
What this `--skip-compile` option does? It worked for me, but I'm a bit afraid in put this on my build
