### ISSUE TITLE
enable hot reloading for sw

### ISSUE THREAD

**Issue by goldylucks** [tszarzynski/cra-append-sw#19]
following #16 , I'd love to have a go of enabling this. I understand you don't want to add it to the core of this plugin, so how about we add a doc for it?

Can you give me any directions about where to start and what files to look into?

thanks!

**Comment by goldylucks** [comment]
btw your project saved my life, YOU ROCK! :rocket:

**Comment by tszarzynski** [comment]
Glad to hear that :)

Have a look at my comment to #16. Try to use the script i'm suggesting. It should probably work like that:

```
run-when-changed --watch "./custom-sw.js" --exec "cra-append-sw --mode dev ./custom-sw.js"
```

If that works fine then we can think about adding an additional option to cra-append-sw script like `--watch`. Or to keep things simple it can also just work as an extension to CRA build scripts, that can be explained in README file.

**Comment by goldylucks** [comment]
so I'm considering ejecting from CRA, too much hassle to work around their shenanigans :)

I'm closing this for now, thanks again for the help!
