### ISSUE TITLE
precache manifest empty

### ISSUE THREAD

**Issue by goldylucks** [tszarzynski/cra-append-sw#20]
I'm using this package like this:

```bash
# package.json.scripts
"build": "react-app-rewired build && cra-append-sw --skip-compile --mode replace ./src/custom-sw.js",
```

and the precache manifest comes out empty. Is this because of `--skip-compile`? If so, what's the workaround?

since without `--skip-compile` I get `can't resolve module babel loader ` (see #19 )

Thanks again for your help

**Comment by tszarzynski** [comment]
It's because of `--mode replace`. In this mode, the SW file created by CRA (with precache manifest) is being completely overridden.

**Comment by goldylucks** [comment]
So how can I get the precache static files generated by CRA webpack build?

**Comment by tszarzynski** [comment]
If you remove ```--mode replace``` the script will append your code to the original CRA service worker code which should contain the precache manifest bits.
