### ISSUE TITLE
babel-loader version conflict with CRA (react-scripts)

### ISSUE THREAD

**Issue by varunj166** [tszarzynski/cra-append-sw#27]
Hey,

I only ran into this problem when I was doing a full reinstall of all my modules. Turns out CRA (currently) wants only babel-loader 8.0.6, but because of the semver in your package.json ("babel-loader": "^8.0.0"), your package is grabbing babel-loader 8.1.0, which CRA complains about when it's time to load its dependencies ("cra-append-sw" comes before "react-scripts" alphabetically, so your deps install first). 

To get around this, I had to install all my modules EXCEPT for cra-append-sw, and then manually re-install cra-append-sw afterward.

This will be a problem during my deploy (coming up soon) because the module install and build steps are triggered automatically, and so they'll fail in the same way on my production server.

I'm not really sure how this issue can be fixed, short of removing "cra-append-sw" from my deps before each deploy, and then adding a postinstall script to install it.

Any ideas?

**Comment by varunj166** [comment]
Alright, the only (real) solution I could find is to use yarn instead of npm. It looks like their dep hoisting is better than npm. 

In my project, removing node_modules, package-lock, and yarn.lock, and then re-installing all deps using "yarn install" was able to dedupe the babel-loader dependency, and everything works fine.

If you've got nothing else to add, you can close this issue.

**Comment by joaomantovani** [comment]
Didn't solve to me, I need to specify the `--skip-compile` option

**Comment by varunj166** [comment]
@joaomantovani If you install cra-append-sw AFTER your complete install of CRA, then npm/yarn should be able to pick up the shared deps (webpack and babel). Just make sure you don't remove your package-lock.json or yarn.lock, which should be keeping track of the overlap. If you do ever need to remove your package-lock/yarn.lock, then you'll have to remove cra-append-sw from your deps, reinstall everything, and then install cra-append-sw separately. 

CRA has very specific versioning in their deps, but cra-append-sw can piggyback off of whatever CRA grabs, so as long as CRA is installed first, cra-append-sw can share what is already in your node_modules.

**Comment by joaomantovani** [comment]
Thanks for the good explanation :)

**Comment by varunj166** [comment]
Sure thing. Hope it works out for ya.
